import type { Metadata } from 'next'
import { Sarabun } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import ChatRooms from '@/components/features/chat/chat-rooms'
import ChatSheet from '@/components/features/chat/chat-sheet'

const sarabun = Sarabun({
  variable: '--font-sarabun',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Hands On Web Chat',
  description: 'Generated by wachirawitS',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className}`}>
        <div className="antialiased bg-zinc-50 h-screen w-screen flex sm:items-center sm:justify-center">
          <div className="mx-auto w-full max-w-4xl px-4 py-4 space-y-4">
            {/* <p className='text-xl text-primary font-bold'>Hands On Web Chat</p> */}
            <div className="h-full sm:h-180 flex gap-4">
              <div className="w-fit h-full hidden sm:block">
                <ChatRooms />
              </div>
              <div className="flex-1">{children}</div>
            </div>
          </div>
        </div>
        <Toaster richColors />
      </body>
    </html>
  )
}
