import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Hands On Web Chat",
  description: "Generated by wachirawitS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className}`}>
        <div className="antialiased flex min-h-screen min-w-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black px-4">
          {children}
        </div>
        <Toaster richColors />
      </body>
    </html>
  );
}
